#!/bin/bash -e
DOCKER=(docker)
DIST=fedora
TRACK() { echo -e "\E[32m$@\E[m" >&2; eval "$@"; }
TRACK "${DOCKER[@]}" build "-${q}t" testhost - "<<-EOF
	FROM $DIST
	RUN mkdir -p /etc/sudoers.d
	RUN echo '$USER ALL=(ALL:ALL) ALL' >/etc/sudoers.d/$USER
	RUN chmod 440 /etc/sudoers.d/$USER
	RUN echo '$USER::$(id -u $USER):$(id -g $USER)::/home/$USER:/bin/bash' >>/etc/passwd
	RUN mkdir -p '/home/$USER'
	RUN chown '$(id -u $USER).$(id -g $USER)' '/home/$USER'
	RUN echo '$USER:x:$(id -g $USER)' >>/etc/group
	CMD [ \"/sbin/init\" ]
	$(case "$DIST" in
		*fedora* | *centos*)
			echo RUN yum install -y \
				systemd git pinentry unzip fuse man-db vim \
				procps
			echo "	RUN dnf clean all"
			;;
		*debian* | *ubuntu* | *mint*)
			echo "RUN apt-get update"
			echo "	"RUN DEBIAN_FRONTEND=noninteractive \
				apt-get install --yes --no-install-recommends \
				curl git vim-gtk gpg gpg-agent sudo \
				systemd-sysv dbus unzip man-db fuse procps
			echo "	RUN apt-get clean"
			;;
	esac)
	RUN sed -i -e\"s/-o '.*'/-a $USER/\" /lib/systemd/system/console-getty.service
	RUN echo 'rm -f /home/$USER/.profile' >>'/home/$USER/.profile'
	RUN echo 'export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR' >>'/home/$USER/.profile'
	RUN echo 'sudo systemctl start user@$(id -u $USER)' >>'/home/$USER/.profile'
	RUN echo 'mkdir -p /run/user/$(id -u $USER)/gnupg' >>'/home/$USER/.profile'
	RUN echo 'ln -sf /home/$USER/.gnupg/S.gpg-agent /run/user/$(id -u $USER)/gnupg/S.gpg-agent' >>'/home/$USER/.profile'
	RUN echo 'PATH="$HOME/.local/bin/yadm:$PATH" bash <(curl -L github.com/cwarlich/yadm/raw/main/bootstrap)' >>'/home/$USER/.profile'
	RUN echo 'exec bash -l' >>'/home/$USER/.profile'
	RUN echo 'sudo halt' >>'/home/$USER/.bash_logout'
	RUN chown $USER.$USER '/home/$USER/.bash_logout'
	RUN mkdir -p /home/$USER/.gnupg
	RUN chown $USER.$USER /home/$USER/.gnupg
	RUN chmod 700 /home/$USER/.gnupg
EOF
"
TRACK "${DOCKER[@]}" run --rm -ithtesthost --privileged \
	-v/run/user/$(id -u $USER)/gnupg/S.gpg-agent:/home/$USER/.gnupg/S.gpg-agent \
	testhost "$@"
